### ISSUE TITLE
remove getters from serialization

### ISSUE THREAD

**Issue by korsvanloon** [Pajn/Warehouse#3]
Hey Pajn,

Great project!
I want my PODO to not store getters because that duplicates data. E.g.:

```dart
class Person {
  String firstName, lastName;
  String get name => '$firstName $lastName';
}
// this will also store 'foo bar' under 'name'
  session.store(new Person()..firstName = 'foo'..lastName = 'bar';
```

My problem is located in `class_lens.dart` -> `_checkDeclarations()`:

```dart
if (!declaration.isPrivate && (
              declaration is VariableMirror ||
              (declaration is MethodMirror && declaration.isGetter)
            ) &&
            !declaration.isStatic) {
```

Can this getter check be removed? Or can this feature be optional somehow?
What was the reasoning for getters te get stored?

**Comment by Pajn** [comment]
The getter support is there on purpose so I wont remove it, but you are right that it should be optional.
I'm thinking about `@ignored` annotations that can be used over all fields to ignore that specific field. Is that good enough for you or do you want some more global control? I'm a bit reluctant to introduce global options because you need to keep them in mind while reading the code to understand what it does, but maybe on a class level would be a good compromise if you feel that it's needed.

**Comment by korsvanloon** [comment]
I agree that the `@ignore` annotation would be the better option.
